package main.java.Chapter1;

/**
 * Autogenerated Class to test Singleton functionality of intellij
 * @author kalbhor
 */
public class testSingleton {
    private static testSingleton ourInstance = new testSingleton();

    public static testSingleton getInstance() {
        return ourInstance;
    }

    private testSingleton() {
    }
}
